export const lavaBlobs = [
  {
    id: 'claro',
    color: '#02C3BD',
    size: '42rem',
    left: '-8%',
    top: '-12%',
    duration: '17s',
    delay: '-4s',
    motion: 'lava-blob-a',
  },
  {
    id: 'vivo',
    color: '#00B9AE',
    size: '36rem',
    left: '48%',
    top: '8%',
    duration: '19s',
    delay: '-9s',
    motion: 'lava-blob-b',
  },
  {
    id: 'profundo',
    color: '#037171',
    size: '38rem',
    left: '18%',
    top: '46%',
    duration: '15s',
    delay: '-2s',
    motion: 'lava-blob-c',
  },
  {
    id: 'medio',
    color: '#009F93',
    size: '28rem',
    left: '62%',
    top: '58%',
    duration: '18s',
    delay: '-12s',
    motion: 'lava-blob-a',
  },
] as const
