export const mediaContent = {
  avatarLabel: 'Foto de perfil',
  avatarHint: 'jpeg, png, webp o avif. Hasta 5 MB. Se verá en tu ficha pública.',
  avatarAlt: 'Foto de perfil',
  avatarEmpty: 'Todavía no hay foto de perfil.',
  avatarSave: 'Guardar foto',
  venueSponsorPhotoLabel: 'Foto de venue sponsor',
  venueSponsorPhotoHint:
    'Muestra el espacio que ofreces. jpeg, png, webp o avif, hasta 5 MB. Obligatoria si eres venue sponsor.',
  venueSponsorPhotoAlt: 'Foto de apoyo como venue sponsor',
  venueSponsorPhotoEmpty: 'Todavía no hay foto de venue sponsor.',
  venueSponsorPhotoSave: 'Guardar foto de venue sponsor',
  localSponsorPhotoLabel: 'Foto de local sponsor',
  localSponsorPhotoHint:
    'Muestra tu emprendimiento o el tipo de aporte. jpeg, png, webp o avif, hasta 5 MB. Obligatoria si eres local sponsor.',
  localSponsorPhotoAlt: 'Foto de apoyo como local sponsor',
  localSponsorPhotoEmpty: 'Todavía no hay foto de local sponsor.',
  localSponsorPhotoSave: 'Guardar foto de local sponsor',
  coverLabel: 'Portada del espacio',
  coverHint: 'Una imagen. jpeg, png, webp o avif, hasta 5 MB.',
  coverAlt: 'Portada del espacio',
  coverSave: 'Guardar portada',
  galleryLabel: 'Galería',
  galleryHint: 'Hasta 8 fotos. Se muestran en la ficha pública.',
  gallerySave: 'Agregar a la galería',
  galleryEmpty: 'Todavía no hay fotos en la galería.',
  galleryRemove: 'Quitar foto',
  evidenceLabel: 'Fotos del evento',
  evidenceHint: 'Opcional. Hasta 8 fotos, jpeg, png, webp o avif, máximo 5 MB cada una.',
  evidenceAlt: 'Foto de evidencia del evento',
  caseGalleryTitle: 'Fotos del caso',
  caseEmpty: 'Este caso no tiene fotos públicas.',
  pendingPhotos: 'Fotos enviadas',
} as const
